// Redux action types
// Naming convention VERB_ENTITY_STATUS

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST'
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS'
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE'

export const UPLOAD_USER_IMAGE_REQUEST = 'UPLOAD_USER_IMAGE_REQUEST'
export const UPLOAD_USER_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS'
export const UPLOAD_USER_IMAGE_FAILURE = 'UPLOAD_USER_IMAGE_FAILURE'

export const FETCH_BUSINESS_REQUEST = 'FETCH_BUSINESS_REQUEST'
export const FETCH_BUSINESS_SUCCESS = 'FETCH_BUSINESS_SUCCESS'
export const FETCH_BUSINESS_FAILURE = 'FETCH_BUSINESS_FAILURE'
export const RESET_BUSINESS = 'RESET_BUSINESS'

export const SET_SEARCH = 'SET_SEARCH'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'

export const POPULATE_SINGLE = 'POPULATE_SINGLE'

export const FETCH_SINGLE_BUSINESS_REQUEST = 'FETCH_SINGLE_BUSINESS_REQUEST'
export const FETCH_SINGLE_BUSINESS_SUCCESS = 'FETCH_SINGLE_BUSINESS_SUCCESS'
export const FETCH_SINGLE_BUSINESS_FAILURE = 'FETCH_SINGLE_BUSINESS_FAILURE'
export const RESET_SINGLE_BUSINESS = 'RESET_BUSINESS'

export const FETCH_BUSINESS_REVIEWS_REQUEST = 'FETCH_BUSINESS_REVIEWS_REQUEST'
export const FETCH_BUSINESS_REVIEWS_SUCCESS = 'FETCH_BUSINESS_REVIEWS_SUCCESS'
export const ADD_REVIEW = 'ADD_REVIEW'

export const CREATE_BUSINESS_REQUEST = 'CREATE_BUSINESS_REQUEST'
export const CREATE_BUSINESS_SUCCESS = 'CREATE_BUSINESS_SUCCESS'
export const CREATE_BUSINESS_FAILURE = 'CREATE_BUSINESS_FAILURE'
